version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - libgirepository1.0-dev
    - libcairo2-dev
    - gir1.2-pango-1.0
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python doc/verilog_doc_parser/rst_doc_generator.py

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - requirements: doc/requirements.txt
