`ifndef REGMAP_PARAMS_VH
`define REGMAP_PARAMS_VH

// Auto-generated from ./regmap.yaml

parameter DMA_BITWIDTH = 64;
parameter TRANSMISSIONS = 6;

// Transmission 0 Offsets
parameter PARAMETER_POS_0_0 = 0;
parameter PARAMETER_POS_0_1 = PARAMETER_POS_0_0 + 8;
parameter PARAMETER_POS_0_2 = PARAMETER_POS_0_1 + 3;
parameter PARAMETER_POS_0_3 = PARAMETER_POS_0_2 + 3;
parameter PARAMETER_POS_0_4 = PARAMETER_POS_0_3 + 1;
parameter PARAMETER_POS_0_5 = PARAMETER_POS_0_4 + 1;
parameter PARAMETER_POS_0_6 = PARAMETER_POS_0_5 + 1;
parameter PARAMETER_POS_0_7 = PARAMETER_POS_0_6 + 4;
parameter PARAMETER_POS_0_8 = PARAMETER_POS_0_7 + 4;
parameter PARAMETER_POS_0_9 = PARAMETER_POS_0_8 + 6;
parameter PARAMETER_POS_0_10 = PARAMETER_POS_0_9 + 4;
parameter PARAMETER_POS_0_11 = PARAMETER_POS_0_10 + 8;

// Transmission 1 Offsets
parameter PARAMETER_POS_1_0 = 0;
parameter PARAMETER_POS_1_1 = PARAMETER_POS_1_0 + 18;
parameter PARAMETER_POS_1_2 = PARAMETER_POS_1_1 + 8;
parameter PARAMETER_POS_1_3 = PARAMETER_POS_1_2 + 8;
parameter PARAMETER_POS_1_4 = PARAMETER_POS_1_3 + 14;

// Transmission 2 Offsets
parameter PARAMETER_POS_2_0 = 0;
parameter PARAMETER_POS_2_1 = PARAMETER_POS_2_0 + 8;
parameter PARAMETER_POS_2_2 = PARAMETER_POS_2_1 + 12;
parameter PARAMETER_POS_2_3 = PARAMETER_POS_2_2 + 8;
parameter PARAMETER_POS_2_4 = PARAMETER_POS_2_3 + 11;
parameter PARAMETER_POS_2_5 = PARAMETER_POS_2_4 + 5;
parameter PARAMETER_POS_2_6 = PARAMETER_POS_2_5 + 4;
parameter PARAMETER_POS_2_7 = PARAMETER_POS_2_6 + 8;
parameter PARAMETER_POS_2_8 = PARAMETER_POS_2_7 + 1;
parameter PARAMETER_POS_2_9 = PARAMETER_POS_2_8 + 1;
parameter PARAMETER_POS_2_10 = PARAMETER_POS_2_9 + 1;
parameter PARAMETER_POS_2_11 = PARAMETER_POS_2_10 + 1;

// Transmission 3 Offsets
parameter PARAMETER_POS_3_0 = 0;
parameter PARAMETER_POS_3_1 = PARAMETER_POS_3_0 + 4;
parameter PARAMETER_POS_3_2 = PARAMETER_POS_3_1 + 8;
parameter PARAMETER_POS_3_3 = PARAMETER_POS_3_2 + 8;
parameter PARAMETER_POS_3_4 = PARAMETER_POS_3_3 + 5;
parameter PARAMETER_POS_3_5 = PARAMETER_POS_3_4 + 6;
parameter PARAMETER_POS_3_6 = PARAMETER_POS_3_5 + 2;
parameter PARAMETER_POS_3_7 = PARAMETER_POS_3_6 + 2;
parameter PARAMETER_POS_3_8 = PARAMETER_POS_3_7 + 4;
parameter PARAMETER_POS_3_9 = PARAMETER_POS_3_8 + 5;
parameter PARAMETER_POS_3_10 = PARAMETER_POS_3_9 + 4;
parameter PARAMETER_POS_3_11 = PARAMETER_POS_3_10 + 1;
parameter PARAMETER_POS_3_12 = PARAMETER_POS_3_11 + 12;

// Transmission 4 Offsets
parameter PARAMETER_POS_4_0 = 0;
parameter PARAMETER_POS_4_1 = PARAMETER_POS_4_0 + 8;
parameter PARAMETER_POS_4_2 = PARAMETER_POS_4_1 + 8;
parameter PARAMETER_POS_4_3 = PARAMETER_POS_4_2 + 4;
parameter PARAMETER_POS_4_4 = PARAMETER_POS_4_3 + 8;
parameter PARAMETER_POS_4_5 = PARAMETER_POS_4_4 + 8;
parameter PARAMETER_POS_4_6 = PARAMETER_POS_4_5 + 4;
parameter PARAMETER_POS_4_7 = PARAMETER_POS_4_6 + 17;

// Transmission 5 Offsets
parameter PARAMETER_POS_5_0 = 0;
parameter PARAMETER_POS_5_1 = PARAMETER_POS_5_0 + 8;
parameter PARAMETER_POS_5_2 = PARAMETER_POS_5_1 + 12;
parameter PARAMETER_POS_5_3 = PARAMETER_POS_5_2 + 1;

`endif // REGMAP_PARAMS_VH
