// Auto-generated from regmap.yaml

parameter DMA_BITWIDTH = 64;
parameter TRANSMISSIONS = 3;

// Transmission 0 Offsets
parameter PARAMETER_POS_0_0 = 0;
parameter PARAMETER_POS_0_1 = PARAMETER_POS_0_0 + 8;
parameter PARAMETER_POS_0_2 = PARAMETER_POS_0_1 + 3;
parameter PARAMETER_POS_0_3 = PARAMETER_POS_0_2 + 3;
parameter PARAMETER_POS_0_4 = PARAMETER_POS_0_3 + 1;
parameter PARAMETER_POS_0_5 = PARAMETER_POS_0_4 + 1;
parameter PARAMETER_POS_0_6 = PARAMETER_POS_0_5 + 1;
parameter PARAMETER_POS_0_7 = PARAMETER_POS_0_6 + 4;
parameter PARAMETER_POS_0_8 = PARAMETER_POS_0_7 + 4;
parameter PARAMETER_POS_0_9 = PARAMETER_POS_0_8 + 4;
parameter PARAMETER_POS_0_10 = PARAMETER_POS_0_9 + 8;
parameter PARAMETER_POS_0_11 = PARAMETER_POS_0_10 + 8;

// Transmission 1 Offsets
parameter PARAMETER_POS_1_0 = 0;
parameter PARAMETER_POS_1_1 = PARAMETER_POS_1_0 + 8;
parameter PARAMETER_POS_1_2 = PARAMETER_POS_1_1 + 8;
parameter PARAMETER_POS_1_3 = PARAMETER_POS_1_2 + 8;
parameter PARAMETER_POS_1_4 = PARAMETER_POS_1_3 + 8;
parameter PARAMETER_POS_1_5 = PARAMETER_POS_1_4 + 11;
parameter PARAMETER_POS_1_6 = PARAMETER_POS_1_5 + 5;
parameter PARAMETER_POS_1_7 = PARAMETER_POS_1_6 + 4;
parameter PARAMETER_POS_1_8 = PARAMETER_POS_1_7 + 8;
parameter PARAMETER_POS_1_9 = PARAMETER_POS_1_8 + 1;
parameter PARAMETER_POS_1_10 = PARAMETER_POS_1_9 + 1;
parameter PARAMETER_POS_1_11 = PARAMETER_POS_1_10 + 1;

// Transmission 2 Offsets
parameter PARAMETER_POS_2_0 = 0;
parameter PARAMETER_POS_2_1 = PARAMETER_POS_2_0 + 1;
parameter PARAMETER_POS_2_2 = PARAMETER_POS_2_1 + 4;
parameter PARAMETER_POS_2_3 = PARAMETER_POS_2_2 + 8;
parameter PARAMETER_POS_2_4 = PARAMETER_POS_2_3 + 8;
parameter PARAMETER_POS_2_5 = PARAMETER_POS_2_4 + 5;
parameter PARAMETER_POS_2_6 = PARAMETER_POS_2_5 + 6;
parameter PARAMETER_POS_2_7 = PARAMETER_POS_2_6 + 2;
parameter PARAMETER_POS_2_8 = PARAMETER_POS_2_7 + 4;
parameter PARAMETER_POS_2_9 = PARAMETER_POS_2_8 + 4;
parameter PARAMETER_POS_2_10 = PARAMETER_POS_2_9 + 5;
parameter PARAMETER_POS_2_11 = PARAMETER_POS_2_10 + 4;

