`ifndef REGMAP_PARAMS_VH
`define REGMAP_PARAMS_VH

// Auto-generated from ./regmap.yaml

parameter DMA_BITWIDTH = 64;
parameter TRANSMISSIONS = 7;

// Transmission 0 Offsets
parameter PARAMETER_POS_0_0 = 0;
parameter PARAMETER_POS_0_1 = PARAMETER_POS_0_0 + 8;
parameter PARAMETER_POS_0_2 = PARAMETER_POS_0_1 + 3;
parameter PARAMETER_POS_0_3 = PARAMETER_POS_0_2 + 3;
parameter PARAMETER_POS_0_4 = PARAMETER_POS_0_3 + 1;
parameter PARAMETER_POS_0_5 = PARAMETER_POS_0_4 + 1;
parameter PARAMETER_POS_0_6 = PARAMETER_POS_0_5 + 1;
parameter PARAMETER_POS_0_7 = PARAMETER_POS_0_6 + 4;
parameter PARAMETER_POS_0_8 = PARAMETER_POS_0_7 + 4;
parameter PARAMETER_POS_0_9 = PARAMETER_POS_0_8 + 6;
parameter PARAMETER_POS_0_10 = PARAMETER_POS_0_9 + 4;
parameter PARAMETER_POS_0_11 = PARAMETER_POS_0_10 + 8;

// Transmission 1 Offsets
parameter PARAMETER_POS_1_0 = 0;
parameter PARAMETER_POS_1_1 = PARAMETER_POS_1_0 + 18;
parameter PARAMETER_POS_1_2 = PARAMETER_POS_1_1 + 16;

// Transmission 2 Offsets
parameter PARAMETER_POS_2_0 = 0;
parameter PARAMETER_POS_2_1 = PARAMETER_POS_2_0 + 16;
parameter PARAMETER_POS_2_2 = PARAMETER_POS_2_1 + 8;
parameter PARAMETER_POS_2_3 = PARAMETER_POS_2_2 + 8;
parameter PARAMETER_POS_2_4 = PARAMETER_POS_2_3 + 14;

// Transmission 3 Offsets
parameter PARAMETER_POS_3_0 = 0;
parameter PARAMETER_POS_3_1 = PARAMETER_POS_3_0 + 8;
parameter PARAMETER_POS_3_2 = PARAMETER_POS_3_1 + 12;
parameter PARAMETER_POS_3_3 = PARAMETER_POS_3_2 + 4;
parameter PARAMETER_POS_3_4 = PARAMETER_POS_3_3 + 4;
parameter PARAMETER_POS_3_5 = PARAMETER_POS_3_4 + 12;
parameter PARAMETER_POS_3_6 = PARAMETER_POS_3_5 + 8;
parameter PARAMETER_POS_3_7 = PARAMETER_POS_3_6 + 11;

// Transmission 4 Offsets
parameter PARAMETER_POS_4_0 = 0;
parameter PARAMETER_POS_4_1 = PARAMETER_POS_4_0 + 4;
parameter PARAMETER_POS_4_2 = PARAMETER_POS_4_1 + 8;
parameter PARAMETER_POS_4_3 = PARAMETER_POS_4_2 + 1;
parameter PARAMETER_POS_4_4 = PARAMETER_POS_4_3 + 1;
parameter PARAMETER_POS_4_5 = PARAMETER_POS_4_4 + 1;
parameter PARAMETER_POS_4_6 = PARAMETER_POS_4_5 + 1;
parameter PARAMETER_POS_4_7 = PARAMETER_POS_4_6 + 1;
parameter PARAMETER_POS_4_8 = PARAMETER_POS_4_7 + 4;
parameter PARAMETER_POS_4_9 = PARAMETER_POS_4_8 + 8;
parameter PARAMETER_POS_4_10 = PARAMETER_POS_4_9 + 8;
parameter PARAMETER_POS_4_11 = PARAMETER_POS_4_10 + 5;
parameter PARAMETER_POS_4_12 = PARAMETER_POS_4_11 + 6;
parameter PARAMETER_POS_4_13 = PARAMETER_POS_4_12 + 1;
parameter PARAMETER_POS_4_14 = PARAMETER_POS_4_13 + 1;
parameter PARAMETER_POS_4_15 = PARAMETER_POS_4_14 + 4;
parameter PARAMETER_POS_4_16 = PARAMETER_POS_4_15 + 5;
parameter PARAMETER_POS_4_17 = PARAMETER_POS_4_16 + 4;

// Transmission 5 Offsets
parameter PARAMETER_POS_5_0 = 0;
parameter PARAMETER_POS_5_1 = PARAMETER_POS_5_0 + 12;
parameter PARAMETER_POS_5_2 = PARAMETER_POS_5_1 + 3;
parameter PARAMETER_POS_5_3 = PARAMETER_POS_5_2 + 8;
parameter PARAMETER_POS_5_4 = PARAMETER_POS_5_3 + 8;
parameter PARAMETER_POS_5_5 = PARAMETER_POS_5_4 + 1;
parameter PARAMETER_POS_5_6 = PARAMETER_POS_5_5 + 8;
parameter PARAMETER_POS_5_7 = PARAMETER_POS_5_6 + 8;

// Transmission 6 Offsets
parameter PARAMETER_POS_6_0 = 0;
parameter PARAMETER_POS_6_1 = PARAMETER_POS_6_0 + 17;
parameter PARAMETER_POS_6_2 = PARAMETER_POS_6_1 + 1;
parameter PARAMETER_POS_6_3 = PARAMETER_POS_6_2 + 8;
parameter PARAMETER_POS_6_4 = PARAMETER_POS_6_3 + 12;
parameter PARAMETER_POS_6_5 = PARAMETER_POS_6_4 + 1;

`endif // REGMAP_PARAMS_VH
